cart/urls.py
from django.urls import path, re_path, include
from . import views


urlpatterns = [

    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
    path('order-sent-successfully/', views.ordersentsuccessfully, name='ordersentsuccessfully'),


]

den/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from shop import views

from django.conf import settings
from django.conf.urls.static import static





urlpatterns = [
     path('admin/', admin.site.urls),
#Сайты
     path('', views.index, name='main'),
     path('delivery', views.page_dostavka, name='delivery'),
     path('catalog/', views.catalog, name='catalog'),
     path('catalog/<str:slug_name>/', views.category_products, name='category_products'),


     path('send-message/', views.send_message, name='send-message'),
     path('message-done/', views.message_done, name='message-done'),
     # path('test2/', views.test2),

     re_path(r'^cart/', include(('cart.urls', 'cart'), namespace='cart'), name='cart'),
     # path('korzina', views.korzina, name='korzina'),
     # re_path(r'^', include(('shop.urls', 'shop'), namespace='shop')),


#Регистрация и авторизация
     path('registration/', views.registration, name='reg'),
     path('login/', views.LoginUser.as_view(), name='login'),
     path('catalog/successfully', views.success, name='success'),
     path('logout/', views.logout_view, name='logout'),

#Вывод одного товара на сайт
     path('catalog/products/<str:slug_tovar>/', views.products_product, name='catalog_tv2'),
]


# включаем возможность обработки картинок
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

class Order(models.Model):

    STATUSORDER_CHOICES = [
        ('N', 'В ожидании'),
        ('W', 'Принят'),
        ('C', 'Завершен'),
    ]

    number = models.CharField(max_length=500, verbose_name='Номер заказчика')
    address = models.CharField(max_length=500, verbose_name='Адрес')
    message = models.CharField(max_length=500, verbose_name='Сообщение', blank=True, null=True)
    price = models.CharField(max_length=100, verbose_name='Стоимость заказа')
    unicnum = models.CharField(max_length=100, verbose_name='Номер заказа')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')
    status = models.CharField(max_length=1, choices=STATUSORDER_CHOICES, verbose_name='Статус заказа')

    class Meta:
        verbose_name = 'Клиента'
        verbose_name_plural = '1. Клиенты'

    def __str__(self):
        return '{}'.format(self.id)


class OrderItem(models.Model):
    product = models.CharField(max_length=150, verbose_name='Имя товара')
    price_1_product = models.CharField(max_length=100, verbose_name='Цена за 1 товар')
    quantity = models.IntegerField(verbose_name='Количество')
    price_all = models.CharField(max_length=100, verbose_name='Общая цена')
    id_order = models.CharField(max_length=100, verbose_name='Номер заказа')

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = '2. Заказы'

    def __str__(self):
        return '{}'.format(self.id)

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(label="Количество:",max_value=20)
    # quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int,label="Количество:")
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

class OrderSave(forms.Form):
    number = forms.IntegerField(label="Ваш номер телефона")
    adres = forms.CharField(max_length=200, label="Адрес доставки (город, улица, квартира)")
    message = forms.CharField(max_length=500, required=False, label="Сообщение (не обязательное поле)")

cart/views.py
import re
import random
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse, HttpResponseNotFound, HttpResponseForbidden, HttpResponseBadRequest, HttpResponseRedirect
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm, OrderSave
from .models import Order, OrderItem


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    # Получить сессию 'cart'
    # sv = (request.session.get('cart'))
    # print(sv)

    massiv3 = []

    for item in cart:
        massiv1 = []
        # print('======================='),
        ts = item['product'],
        # Перевод получаемого айди в integer, numbers[0]
        numbers = re.findall(r'\b\d+\b', (str(ts)))
        cenazatovar = item['price']
        # print('Цена за шт',cenazatovar)
        kolvo = item['quantity']
        # print('Кол-во приобретаемого товара', cenazatovar)
        total_item = item['price'] * item['quantity']
        # print('Итоговая сумма товара', total_item)
        product_poisk = Product.objects.filter(id=(int(numbers[0])))
        # Перебор массива для вывода получаемых данных
        for person in product_poisk:
            nametovar = [person.name]

        # Запись всех данных в список
        massiv1.append(nametovar[0])
        massiv1.append(int(cenazatovar))
        massiv1.append(int(kolvo))
        massiv1.append(int(total_item))

        # Запись списка в другой список
        massiv3.append(massiv1)

    # print(massiv3)

    form = OrderSave()

    if request.method == "POST":
        form = OrderSave(request.POST)
        if form.is_valid():
            unicn = random.uniform(0, 100)
            number = request.POST.get("number")
            adres2 = request.POST.get("adres")
            message2 = request.POST.get("message")
            priceorder = request.POST.get("price")

            element = Order(number=number, address=adres2, message=message2, price=str(priceorder) + ' ₽',
                            unicnum=unicn, status='N')
            element.save()

            for sv in massiv3:
                name = sv[0]
                price_van_tovar = str(sv[1]) + ' ₽'
                kolvotovara = sv[2]
                priceall = str(sv[3]) + ' ₽'
                element = OrderItem(product=name, price_1_product=price_van_tovar, quantity=kolvotovara,
                                    price_all=priceall, id_order=unicn)
                element.save()

            cart.clear()
            massiv3.clear()
            return HttpResponseRedirect('/cart/order-sent-successfully/')


        else:
            form = OrderSave()

    massiv3.clear()

    # Генерация случайного числа от 0 до 100 (0.9239781787291634)
    # print(random.uniform(0, 100))
    return render(request, 'cart/korzina.html', {'cart': cart, 'form': form, })


def ordersentsuccessfully(request):
    return render(request, "cart/ordersentsuccessfully.html")

cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}
    <h1>Корзина товаров</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Фото</th>
            <th>Товар</th>
            <th>Кол-во  </th>
            <th>Цена,шт  </th>
            <th>Общая цена  </th>
            <th>Удалить</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static "img/no_image.png" %}
                                {% endif %}">
                        </a>
                    </td>
                    <td data-label="Товар">{{ product.name }}</td>
                    <td data-label="Кол-во">{{ item.quantity }}</td>
                    <td data-label="Цена,шт" class="num">{{ item.price }} ₽</td>
                    <td data-label="Цена" class="num">{{ item.total_price }} ₽</td>
                    <td data-label="Удалить"><a href="{% url "cart:cart_remove" product.id%}">Удалить</a></td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Итоговая сумма</td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price }} ₽</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="" class="button light">Продолжить покупки</a>
    </p>
{% endblock %}

cart/templates/cart/korzina.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css\korzina.css'%}">

    <title>Document</title>
    <style>
        input {width: 100%;}
        body, :root {background-color:#ecf6d9}
        .modal-header,.modal-body,.modal-footer {background-color: #fffdf3;}
    </style>
</head>

<header>
<ul class="menu">
  <li><a href="{% url 'catalog' %}">Вернуться к каталогу</a></li>
</ul>

{% with total_items=cart|length %}
    {% if cart|length > 0 %}
        <button class="cart" id="cart">
          <img class="cart__image" src="{% static '/img/cart.png' %}" width="75px" height="50px" alt="Cart" />
          <div class="cart__num" id="cart_num">{{ total_items }}</div>
        </button>



    {% else %}
        <button class="cart" id="cart">
          <img class="cart__image" src="{% static '/img/cart.png' %}" width="75px" height="50px" alt="Cart" />
          <div class="cart__num" id="cart_num">{{ total_items }}</div>
        </button>


    {% endif %}
{% endwith %}
</header>


<body>
<div class="shopping-cart">
    {% with total_items=cart|length %}
    {% if cart|length > 0 %}

      <div class="title3">
            <div class="naimenovania">
                <p class="p1">Фото</p>
                <p class="p2">Имя товара</p>
                <p class="p3">Количество</p>
                <p class="p4">Цена</p>
            </div>
      </div>

      <!-- Товар #1 -->


    {% for item in cart %}
        {% with product=item.product %}
          <div class="item">
            <div class="image">
              <img src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static "img/no_image.png" %}
                                {% endif %}" width="150px" height="150px" alt="" />
            </div>

            <div class="description2">
              <p>{{ product.name }}</p>
            </div>
              <div class="total-price2">{{ item.quantity }} шт</div>
            <div class="total-price2">{{ item.total_price }} ₽</div>

            <div class="buttons-delete"><a href="{% url "cart:cart_remove" product.id%}"><button class="del-b">Удалить товар</button></a>

            </div>
          </div>
        {% endwith %}

    {% endfor %}
<div class="get-total-price" >Итоговая цена за {{ total_items }} шт. <p>{{ cart.get_total_price }} ₽</p> </div>
</div>




  <!-- Модальное окно -->
      <div class="modal-content" style="min-width: 300px;">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel" >Отправьте ваш заказ</h5>
<!--          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>-->
        </div>
        <div class="modal-body">
        <form method="POST">
            {% csrf_token %}
            <div>
            {{ form.as_p }}
            </div>
            <input name="price" value="{{ cart.get_total_price }}" readonly style="display: none">
            <input type="submit" style="font-size: 17px" value="  Отправить  ">
        </form>
        </div>
        <div class="modal-footer">
        </div>
      </div>



    {% else %}

      <div class="title" >
            Shopping
      </div>
      <div class="title2" style="padding: 30px;">
            Корзина пустая
      </div>
    </div>

    {% endif %}
{% endwith %}

<footer></footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

cart/templates/cart/ordersentsuccessfully.html
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Document</title>
    <style>
        input {width: 100%;}
        body, :root {background-color:#dbeded}
        .modal-content {min-width: 300px;}
        .modal-header,.modal-body,.modal-footer {background-color: #fffdf3;
        .test-mo {font-weight: normal;}
    </style>
</head>

<body>

  <!-- Модальное окно -->
      <div class="modal-content" style="width: 34%;margin: 10% 35%">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ваше заказ успешно отправлен!</h5>
<!--          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>-->
        </div>
        <div class="modal-body">
        <h5 class="test-mo"><br>Ожидайте</h5>
        </div>
        <div class="modal-footer">
        <form action="{% url 'catalog' %}">
            <button type="submit" class="btn btn-secondary" data-bs-dismiss="modal">Вернуться к товарам</button>
        </form>
        <form action="{% url 'main' %}">
            <button type="submit" class="btn btn-secondary" data-bs-dismiss="modal">Вернуться на главную страницу</button>
        </form>
<!--          <button type="button" class="btn btn-primary">Сохранить изменения</button>-->
        </div>
      </div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>