cart/urls.py
from django.urls import path, re_path, include
from . import views


urlpatterns = [

    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
    path('order-sent-successfully/', views.ordersentsuccessfully, name='ordersentsuccessfully'),


]

den/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from shop import views

from django.conf import settings
from django.conf.urls.static import static





urlpatterns = [
     path('admin/', admin.site.urls),
#Сайты
     path('', views.index, name='main'),
     path('delivery', views.page_dostavka, name='delivery'),
     path('catalog/', views.catalog, name='catalog'),
     path('catalog/<str:slug_name>/', views.category_products, name='category_products'),


     path('send-message/', views.send_message, name='send-message'),
     path('message-done/', views.message_done, name='message-done'),
     # path('test2/', views.test2),

     re_path(r'^cart/', include(('cart.urls', 'cart'), namespace='cart'), name='cart'),
     # path('korzina', views.korzina, name='korzina'),
     # re_path(r'^', include(('shop.urls', 'shop'), namespace='shop')),


#Регистрация и авторизация
     path('registration/', views.registration, name='reg'),
     path('login/', views.LoginUser.as_view(), name='login'),
     path('catalog/successfully', views.success, name='success'),
     path('logout/', views.logout_view, name='logout'),

#Вывод одного товара на сайт
     path('catalog/products/<str:slug_tovar>/', views.products_product, name='catalog_tv2'),
]


# включаем возможность обработки картинок
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models


# from django.conf import settings
# from django.contrib.auth.models import User




class Category(models.Model):
    name = models.TextField()
    slug = models.SlugField(null=False, unique=True)
    image = models.ImageField(blank=True, null=True, verbose_name='Картинка')
    image2 = models.ImageField(blank=True, null=True, verbose_name='Картинка2')

    class Meta():
        verbose_name_plural = "2. Категории"
        verbose_name = "Категорию"

    def __str__(self):
        return f"{self.id}, {self.name}"


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='Имя товара')
    slug = models.SlugField(null=False, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория товара')
    description = models.TextField(null=True, blank='None', verbose_name='Описание')
    price = models.IntegerField(verbose_name='Цена')
    image = models.ImageField(blank=True, null=True, verbose_name='Картинка')
    image2 = models.ImageField(blank=True, null=True, verbose_name='Картинка2')

    class Meta():
        verbose_name_plural = "1. Товары"
        verbose_name = "Товар"

    # def __str__(self):
    #     return f"{self.id}, {self.name}, Категория продукта - {self.category_id}"

    def __str__(self):
        return 'Obj: {}'.format(self.id)


class Svyaz(models.Model):
    message = models.TextField(verbose_name='Сообщение')
    number = models.TextField()
    email = models.TextField()
    datetime = models.TextField()

    class Meta():
        verbose_name_plural = "3. Сообщения от пользователей"
        verbose_name = "Запись"

shop/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from shop.views import *
# from shop.models import svyaz

class RegForm(forms.ModelForm):
    username = forms.CharField(label="Логин")
    password = forms.CharField(label="Пароль", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Повтор пароля", widget=forms.PasswordInput)

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'nickname': 'Прозвище',
        }

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("Пароли не совпадают!")
        return cd['password2']

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))


    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class UserForm(forms.Form):
    message = forms.CharField(max_length=500, label="Ваше сообщение")
    number = forms.IntegerField(label="Ваш номер телефона")
    email = forms.EmailField(max_length=255, label="Ваш email")

shop/views.py
import json, re, ast
from datetime import datetime
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse, HttpResponseNotFound, HttpResponseForbidden, HttpResponseBadRequest, HttpResponseRedirect
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_exempt
from .models import Category, Product, Svyaz
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.contrib.auth import logout
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, get_object_or_404
from .forms import LoginUserForm, RegForm, UserForm

#korzina
from cart.forms import CartAddProductForm



def index(request):
    tovars = Product.objects.filter(id__in=[5, 27, 38, 51])

    context = {
        'pr': tovars,
    }
    return render(request, 'index.html', context)


def page_dostavka(request):
    return render(request, "dostavka.html")


def catalog(request):
    tovar = Category.objects.all().order_by('id')
    tv = {
        'tv': tovar,
    }

    return render(request, "katalog.html", tv)

def category_products(request, slug_name):
    category_poisk = Category.objects.filter(slug=slug_name)
    for person in category_poisk:
        id_cat = person.id
        tovars = Product.objects.filter(category=id_cat)




    context = {
        'pr': tovars,
    }

    return render(request, "tovari.html", context)


# Вывод отдельного товара на страничку html
def products_product(request, slug_tovar):
    product_poisk = Product.objects.filter(slug=slug_tovar)
    for person in product_poisk:
        id_cat = person.id
        tovars = Product.objects.filter(id=id_cat)

    cart_product_form = CartAddProductForm()


    context = {
        'pr': tovars,
        'cart_product_form': cart_product_form,
    }

    return render(request, "opisanietovara.html", context)



# def product_detail(request, id, slug):
#     product = get_object_or_404(Product,
#                                 id=id,
#                                 slug=slug,
#                                 available=True)
#     cart_product_form = CartAddProductForm()
#     return render(request, 'shop/product/detail.html', {'product': product,
#                                                         'cart_product_form': cart_product_form})


def send_message(request):
    ccurrent_datetime = datetime.now()
    current_datetime = str(ccurrent_datetime)
    print(current_datetime)

    form = UserForm()

    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            message2 = request.POST.get("message")
            number = request.POST.get("number")
            email = request.POST.get("email")
            date = request.POST.get("date")
            element = Svyaz(message=message2, number=number, email=email, datetime=date)
            element.save()

            return HttpResponseRedirect('/message-done/')

        else:
            form = UserForm()
            print('lox')

    context = {
        'form': form, 'current_datetime': current_datetime
    }
    return render(request, "send-message.html", context)

def message_done(request):
    return render(request, "message_done.html")


# Функции авторизации и регистрации
def registration(request):
    if request.method == "POST":
        form = RegForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)  # создание объекта без сохранения в БД
            user.set_password(form.cleaned_data['password'])
            user.save()
            return render(request, 'registration_done.html')
    else:
        form = RegForm()
    return render(request, 'reg.html', {'form': form})


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'login.html'
    extra_context = {'title': "Авторизация"}

    def get_success_url(self):
        return reverse_lazy('success')


# Успешная авторизация
def success(request):
    html = redirect('/catalog')
    html.set_cookie('authorization', 'successful authorization', max_age=None)
    stt = request.COOKIES.get('authorization')
    print(stt)
    return html


# Выход из аккаунта
def logout_view(request):
    logout(request)

    html = redirect('/catalog')
    html.delete_cookie("authorization")
    return html





    # Перебор массива и передача его в (массив - python)
    # test3 = ['1','10','6']
    # people = product.objects.filter(id__in=test3).order_by('id')
    #
    # for person2 in people:
        # print(f"{person2.id} {person2.name} {person2.price}")
        # test2 = [person2.id, person2.name, person2.price]
        # print(test2)



    # Перебор массива для вывода получаемых данных
    # for person in people:
    #     print(f"{person.id}.{person.name} - {person.age}")


    # Вывод данных с 1 по 12 айди
    # people = productinformation.objects.filter(id__range=(1, 12))

shop/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css\base.css'%}">
    {% block cssstyle %} {% endblock %}
    <title>Document</title>
</head>
<body>
<header class="header">
        <div class="logo"><img src="{% static '/img/logo.png' %}" alt="" width="245px" height="140px"></div>

        <!-- Меню для телефонов -->
            <!-- Hamburger icon -->
            <input class="side-menu" type="checkbox" id="side-menu"/>
            <label class="hamb" for="side-menu"><img src="{% static '/img/menu.png' %}" alt="" width="100px " height="100px" ></span></label>
            <!-- Menu -->
            <nav class="nav">
                <ul class="menu">
                    <li><a href="{% url 'catalog' %}">Каталог товаров</a></li>
                    <li><a href="{% url 'delivery' %}">Доставка</a> </li>
                    <li><a href="{% url 'main' %}">Главная</a></li>
                    <li><a href="/cart">Корзина</a></li>
                    <li class="authorize-small-resolution" >
                        {% if user.is_authenticated %}
                        <p><a>Ваше имя пользователя - {{user.username}} <a href="{% url 'logout' %}">Выйти из аккаунта</a></a></p>

                        {% else %}
                          <a href="{% url 'login' %}">Вход</a>
                          <a href="{% url 'reg' %}">Регистрация</a>
                        {% endif %}
                    </li>
                </ul>
            </nav>
        <!-- end -->

            <div class="line"></div>
            <div class="adres"><h1>Г. Шумерля, улица Ленина,  дом 24</h1></div>
                 <div class="auth">
                    {% if user.is_authenticated %}
                    <p><a href="">{{user.username}}</a></p>
                    <p><a href="{% url 'logout' %}">Выйти</a></p>
                    {% else %}
                      <a href="{% url 'login' %}">Вход</a>
                      <a href="{% url 'reg' %}">Регистрация</a>
                    {% endif %}
                 </div>

                <div class="knopki">
                    <ul>
                        <li><a href="{% url 'catalog' %}" class="button_01">Каталог товаров</a></li>
                        <li><a href="{% url 'delivery' %}" class="button_01">Доставка</a></li>
                        <li><a href="{% url 'main' %}" class="button_01">Главная</a></li>
                {% with total_items=cart|length %}
                    {% if cart|length > 0 %}
                        <li><a href="/cart" class="button_01">Корзина<p class="cart__num" id="cart_num">{{ total_items }}</p></a></li>
                    {% else %}
                        <li><a href="/cart" class="button_01">Корзина</a></li>
                    {% endif %}
                {% endwith %}
                    </ul>
                </div>
</header>
<main>
{% block content %}

{% endblock %}
</main>


<footer></footer>

{% block js %}
{% endblock %}

</body>
</html>

shop/templates/dostavka.html
{% extends 'base.html' %}
{% load static %}

{% block cssstyle %}
    <link rel="stylesheet" href="{% static 'css\index.css'%}">
{% endblock %}



{% block content %}
    <div class="dannie-dostavka">
        <div class="text-dostavka">
            <h1>Добро пожаловать в интернет-магазин «Бытовая техника»</h1>
                <p> Время работы магазина: 09:00 – 18:00 (пн – пт) <br> <br>
                    Телефон: +7 (965) 689-26-78 <br><br>
                    Уважаемые покупатели! <br><br>
                    Cпособом общения является направление вашего обращения по <br>  (<a href="{% url 'send-message' %}">Форме обратной связи</a>).
                </p>

                    <h1>Оплата товаров</h1>
                        <div class="visamastercardsberbank"><img src="{% static 'img\glavnaya\visamastercardsberbank.png'%}" style="width: 100%;height: 100%;"></div>
                            <p>Способы оплаты:<br></p>

                                <p class="center">Наличный расчёт:</p><br>
                                    <p>Если товар доставляется курьером, то оплата осуществляется наличными курьеру в руки. При получении товара обязательно проверьте комплектацию товара, наличие гарантийного талона и чека.</p><br><br>


                                    <p class="center">Банковской картой: </p><br>
                                        <p>Оплата происходит через ПАО СБЕРБАНК с использованием банковских карт следующих платёжных систем:</p>
                                            <ul>
                                                <li>Мир</li>
                                                <li>VISA International</li>
                                                <li>Mastercard Worldwide</li>
                                            </ul>

        </div>
    </div>
{% endblock %}




    

shop/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block cssstyle %}
    <link rel="stylesheet" href="{% static 'css\index.css'%}">
{% endblock %}



{% block content %}
<div class="main-block"><p>В интернет-магазине представлен большой ассортимент товаров по доступным ценам.<br> У нас действует удобная доставка до Вашего дома<br>
Вы можете быстро и недорого купить любые товары в удобное время суток!</p>
    <div class="main-block-knopka" >
        <a href="{% url 'catalog' %}" class="button_1711202609292">Каталог товаров</a>
    </div>
</div>

    <div class="main-block2">


<div class="main-block2-brend"><h1>Бренды</h1></div>
            <div class="block2-brend-cart">

<!--                <div class="block2-brend-cart-2">-->
                    <div class="brend-cart-1"><img src="{% static 'img\glavnaya\lg.png'%}"></div>
                    <div class="brend-cart-1"><img src="{% static 'img\glavnaya\samsung.png'%}"></div>
                    <div class="brend-cart-1"><img src="{% static 'img\glavnaya\sony.png'%}"></div>
                    <div class="brend-cart-1"><img src="{% static 'img\glavnaya\electrolix.png'%}"></div>
                    <div class="brend-cart-1"><img src="{% static 'img\glavnaya\bosch.png'%}"></div>
                    <div class="brend-cart-1"><img src="{% static 'img\glavnaya\haier.png'%}"></div>
                    <div class="brend-cart-1"><img src="{% static 'img\glavnaya\roca.png'%}"></div>
                    <div class="brend-cart-1"><img src="{% static 'img\glavnaya\philips.png'%}"></div>
<!--                </div>-->
            </div>
    </div>

<div class="main-block3"><div class="main-block3-zagolovok"><h1>Популярные товары</h1></div>
            <div class="main-block3-box">

                {% for post in pr %}
                <div class="main-block3-tovar" id="{{ post.id }}"><a href="/catalog/products/{{ post.slug }}"><img src="/static/img/{{ post.image }}" width="240px" height="200" alt=""></a><h1>{{ post.price }} ₽</h1>
                    <div class="main-block3-nazvanie">
                        <a href="/catalog/products/{{ post.slug }}">{{ post.name }}</a>
                    </div>
                        <div class="main-block3-ktovary">
                            <a class="button_166" href="/catalog/products/{{ post.slug }}" >Перейти к товару</a>
                        </div>
                </div>
                {% endfor %}
            </div>
</div>




{% endblock %}

shop/templates/katalog.html
{% extends 'base.html' %}
{% load static %}

{% block cssstyle %}
    <link rel="stylesheet" href="{% static 'css\catalog.css'%}">
{% endblock %}



{% block content %}
    <div class="glav-catalog">
        <a href="{% url 'main' %}" class="glav-a" >Главная -</a>
        <a href="#"  class="glav-a" > Каталог товаров </a>
    </div>

    <div class="tovari-catalog">
        {% for post in tv %}
        <a href="/catalog/{{ post.slug }}/" class="tovari-catalog-a"><img src="/static/img/{{ post.image }}" width="148px" height="83.02" ><h1>{{ post.name }}</h1></a>
        {% endfor %}
    </div>

{% endblock %}

{% block js %}
<script src="{% static 'js\order.js' %}"></script>
{% endblock %}

shop/templates/korzina.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css\korzina.css'%}">

    <title>Document</title>
    <style>
        input {width: 100%;}
        body, :root {background-color:#ecf6d9}
        .modal-header,.modal-body,.modal-footer {background-color: #fffdf3;}
    </style>
</head>

<header>

<ul class="menu">
  <li><a href="{% url 'catalog' %}">Вернуться к каталогу</a></li>
</ul>

</header>

<body>
<div class="shopping-cart">
      <!-- Title -->
      <div class="title">
        Shopping
      </div>
      <div class="title2">
        Корзина пустая
      </div>

      <!-- Товар #1 -->


      <div class="item">
        <div class="image">
          <img src="/static/img/{{ post.image }}" width="150px" height="150px" alt="" />
        </div>

        <div class="description2">
          <p>Описание товара</p>
        </div>
        <div class="total-price2">Цена товара ₽</div>

        <div class="buttons-delete">
          <button class="del-b" >Удалить товар</button>
        </div>
      </div>

    {% for post in tv %}
      <div class="item">
        <div class="image">
          <img src="/static/img/{{ post.image }}" width="150px" height="150px" alt="" />
        </div>

        <div class="description2">
          <p>{{ post.name }}</p>
        </div>
        <div class="total-price2">{{ post.price }} ₽</div>

        <div class="buttons-delete">
          <button class="del-b" >Удалить товар</button>
        </div>
      </div>
    {% endfor %}
</div>

  <!-- Модальное окно -->
      <div class="modal-content" style="min-width: 300px;">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel" >Отправьте ваш заказ</h5>
<!--          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>-->
        </div>
        <div class="modal-body">
        <form method="POST">
            {% csrf_token %}
            <div>
            {{ form.as_p }}
            </div>
            <input name="date" value="{{ current_datetime }}" readonly style="display: none">
            <input type="submit" style="font-size: 17px" value="  Отправить  ">
        </form>
        </div>
        <div class="modal-footer">
        </div>
      </div>

<footer></footer>

<script src="{% static 'js\bascket.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>

shop/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block cssstyle %}
<link rel="stylesheet" href="{% static 'css\loginreg.css'%}">
{% endblock %}

{% block content %}
<div class="login">
    {% block regwindow %}

    <main>
        <h1>Авторизация</h1><br>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <p><button type="submit" class="submit">Войти</button></p>
        </form>
        <br>
        <h2>Если вы не зарегистрированы то зарегистрируйтесь по этой ссылке <a href="{% url 'reg' %}">ссылке</a></h2>
    </main>

    {% endblock regwindow %}
</div>
{% endblock %}

shop/templates/message_done.html
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Document</title>
    <style>
        input {width: 100%;}
        body, :root {background-color:#dbeded}
        .modal-content {min-width: 300px;}
        .modal-header,.modal-body,.modal-footer {background-color: #fffdf3;
        .test-mo {font-weight: normal;}
    </style>
</head>

<body>

  <!-- Модальное окно -->
      <div class="modal-content" style="width: 34%;margin: 10% 35%">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ваше сообщение успешно отправлено!</h5>
<!--          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>-->
        </div>
        <div class="modal-body">
        <h5 class="test-mo"><br>Ожидайте звонка или сообщения на почту</h5>
        </div>
        <div class="modal-footer">
        <form action="{% url 'main' %}">
            <button type="submit" class="btn btn-secondary" data-bs-dismiss="modal">Вернуться на главную страницу</button>
        </form>
<!--          <button type="button" class="btn btn-primary">Сохранить изменения</button>-->
        </div>
      </div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

shop/templates/opisanietovara.html
{% extends 'base.html' %}
{% load static %}

{% block cssstyle %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css\opisanietovara.css'%}">
{% endblock %}

{% block content %}
    {% for post in pr %}
        <div class="soder-kart"><img src="/static/img/{{ post.image2 }}" alt=""></div>

        <div class="soder">
            <div class="nazvanie-soder" id="{{ post.id }}">
                {{ post.name }}
            </div>
                <h1>Все характеристики:</h1>
                    <div class="tovar-any-opisanie">
                        <p>
                            {{ post.description|linebreaksbr }}
                        </p>
                    </div>


         <div class="buyblock">
            <h1>{{ post.price }} ₽</h1>
            <form class="addtocart" action="{% url "cart:cart_add" post.id %}" method="post">
                {{ cart_product_form }}
                {% csrf_token %}
                <div class="buyblock-knopka" ><input type="submit" value="Купить" class="button_166"></div>
            </form>

         </div>

<!--            <form class="addtocart" action="{% url "cart:cart_add" post.id %}" method="post">-->
<!--                {{ cart_product_form }}-->
<!--                {% csrf_token %}-->
<!--                <input type="submit" value="Add to cart">-->
<!--            </form>-->
        </div>
    {% endfor %}


<!-- Кнопка-триггер модального окна -->
<!--<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">-->
<!--  Запустите демо модального окна-->
<!--</button>-->

<!-- Модальное окно -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
      </div>
      <div class="modal-body" >
        Авторизируйтесь для покупки товара
      </div>
      <div class="modal-footer">
        <form action="{% url 'login' %}">
            <button type="submit" class="btn btn-primary">Авторизироваться</button>
        </form>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}







{% block js %}
<script src="{% static 'js\order.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% endblock %}

shop/templates/reg.html
{% extends 'base.html' %}
{% load static %}

{% block cssstyle %}
<link rel="stylesheet" href="{% static 'css\loginreg.css'%}">
{% endblock %}

{% block content %}

    {% block regwindow %}
    <div class="regwindow">
            <div class="currentform">
                <h1>Регистрация:</h1><br>
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}<br>
                    <button type="submit">Зарегистрироваться</button>
                </form>
            </div>
    </div>
    {% endblock regwindow %}

{% endblock %}

shop/templates/registration_done.html
{%load static%}
{% block regwindow %}

    <div class="regwindow">
        <h1 >Добро пожаловать!</h1>

        <p style="font-size: 25px;">Вы успешно зарегистрировались на сайте! Для входа в систему необходимо авторизоваться по этой <a href="{% url 'login' %}">ссылке</a></p>
    </div>


{% endblock regwindow %}

shop/templates/tovari.html
{% extends 'base.html' %}
{% load static %}

{% block cssstyle %}

<link rel="stylesheet" href="{% static 'css\tovari.css'%}">
{% endblock %}




{% block content %}
    <div class="glav-catalog">
        <a href="{% url 'main' %}" class="glav-a" >Главная -</a>
        <a href="{% url 'catalog' %}"  class="glav-a" > Каталог товаров </a>
    </div>

            <div class="box">
                {% for post in pr %}
                <div class="tovar" id="{{ post.id }}"><a href="/catalog/products/{{ post.slug }}"><img src="/static/img/{{ post.image }}" width="240px" height="200" alt=""></a><h1>{{ post.price }} ₽</h1>
                    <div class="nazvanie">
                        <a href="/catalog/products/{{ post.slug }}">{{ post.name }}</a>
                    </div>
                        <div class="vkorziny">
                            <a class="button_166" href="/catalog/products/{{ post.slug }}" >Перейти к товару</a>
                        </div>
                </div>
                {% endfor %}
            </div>
{% endblock %}